### ISSUE TITLE
P2pool failing

### ISSUE THREAD

**Issue by brainchainz** [hinto-janaiyo/gupax#2]
I'm having issues running P2pool in both simple mode:

2022-12-15 10:07:47.9910 StratumServer failed to listen on tcp server socket [::]:3333, error EADDRINUSE
2022-12-15 10:07:47.9911 Log stopped

and advanced mode, trying to connect to local monero node:

2022-12-15 10:07:30.4385 P2Pool get_info RPC request failed: error Couldn't connect to server (empty response), trying again in 1 second

**Comment by hinto-janaiyo** [comment]
>StratumServer failed to listen on tcp server socket [::]:3333, error EADDRINUSE

This means you already have something open on port 3333, so P2Pool can't start

The 2nd one means P2Pool can't connect to the Monero node specified, do you have a node running on the same machine with ZMQ enabled?

**Comment by brainchainz** [comment]
monero gui on same system- how do i enable zmq?

**Comment by brainchainz** [comment]
how do i find out what else is on 3333 or change p2pool's port?

**Comment by hinto-janaiyo** [comment]
ZMQ In Monero-GUI: Settings -> Node -> Daemon startup flags -> Type in: `zmq-pub=tcp://127.0.0.1:18083`

The 2nd one depends on your OS, use google.

**Comment by brainchainz** [comment]
Gupax freezes anytime I switch to another window.
Also, after adding the flag. p2pool still does not connect:
P2Pool get_info RPC request failed: error URL using bad/illegal format or
missing URL (empty response), trying again in 1 second

**Comment by hinto-janaiyo** [comment]
[Here's some documentation for node operation.](https://monerodocs.org/interacting/monerod-reference) You can also just use a community node (P2Pool simple).

>Gupax freezes anytime I switch to another window

Can you provide a video of this happening?

**Comment by brainchainz** [comment]
> 


https://user-images.githubusercontent.com/100279867/208215084-95c54346-d50f-4dd7-a393-5dd74cf5784e.mov

**Comment by hinto-janaiyo** [comment]
There's no video, it's just audio.
